services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cat_sql_server
    environment:
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
